# Generated by Django 5.2.4 on 2025-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadanía'), ('CE', 'Cedula de extranjeria'), ('TI', 'Tarja de Identidad'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=200, null=True)),
                ('nivel_educativo', models.CharField(choices=[('TEC', 'Tecnico'), ('TGL', 'Tecnologo'), ('PRE', 'Pregrado'), ('ESP', 'Especializacion'), ('MAE', 'Maestria'), ('DOC', 'Doctorado')], default='MAE', max_length=3)),
                ('especialidad', models.CharField(max_length=200)),
                ('anos_experiencia', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateField(null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
